project 'ReactionApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
  
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'

target 'ReactionApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactionApp
  
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  
  pod 'Charts/Realm'
  
  pod 'RandomKit', '~> 3.0.0'
  
  pod 'RAMAnimatedTabBarController', "~> 2.0.13"
  
  pod 'LTMorphingLabel'
  
  pod 'Eureka', '~> 2.0'

  target 'ReactionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactionAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
