project 'ReactionApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
  
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'

target 'ReactionApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactionApp
  
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  
  pod 'Charts'
  pod 'ChartsRealm'
  
  pod 'Google-Mobile-Ads-SDK'
  
  pod 'RandomKit', :git => 'https://github.com/nvzqz/RandomKit.git'
  
  pod 'RAMAnimatedTabBarController'
  
  pod 'LTMorphingLabel'
  
  pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'
  
  pod 'PopupDialog', '~> 0.6'
  
  pod 'Sparrow/Modules/RequestPermission', :git => 'https://github.com/IvanVorobei/Sparrow.git’

  target 'ReactionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactionAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
